[theme]
primaryColor = "#fda4af"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
port = 8505
enableCORS = false
enableXsrfProtection = false
